# Generated by Django 2.0.12 on 2023-06-09 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledgebase', '0002_auto_20230609_0830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='knowledgebase',
            options={'ordering': ['-name']},
        ),
        migrations.RenameField(
            model_name='knowledgebase',
            old_name='fileName',
            new_name='name',
        ),
    ]
